### ISSUE TITLE
fix: wrongly tagged twitter badge

### ISSUE THREAD

**Issue by kumarsonsoff3** [Badbatunde/Badbatunde#1]
> Twitter badge in the Readme is tagged with a wrong link. 

The Twitter badge used in the readme is taking the visitors to `EddieJaoude`'s Profile instead of your's `badbatunde`.
![image](https://user-images.githubusercontent.com/88786642/183472804-f132ae2a-efc5-4441-a86f-0795ac457c01.png)

**Comment by Badbatunde** [comment]
Oh, this would be rectified as soon as possible. Thank you.

**Comment by Badbatunde** [comment]
This has been resolved, thanks.

**Comment by kumarsonsoff3** [comment]
Great! You're so fast 🚀
Keep up the great work! 😄
